
version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: psych_db
    restart: always
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    container_name: psych_app
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://johndoe:randompassword@postgres:5432/mydb?schema=public"

volumes:
  db-data:
